services:
  postgres:
    image: postgres:17

    container_name: dpsm-postgres

    restart: unless-stopped

    environment:
      POSTGRES_DB: dpsm
      POSTGRES_USER: dpsm
      POSTGRES_PASSWORD: dpsm

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

  directus:
    image: directus/directus:latest

    container_name: dpsm-directus

    restart: unless-stopped

    ports:
      - "8055:8055"

    environment:
      SECRET: super-secret-key

      ADMIN_EMAIL: admin@example.com
      ADMIN_PASSWORD: admin123

      DB_CLIENT: pg

      DB_HOST: postgres
      DB_PORT: 5432

      DB_DATABASE: dpsm
      DB_USER: dpsm
      DB_PASSWORD: dpsm

    depends_on:
      - postgres

volumes:
  postgres_data:
